import os

"""
Stock Overflow Data Paths

Forward slashes are used on purpose: they work on Windows and the file helpers (so.core.local_file_management) expect them.
The data root can be overridden with the environment variable SO_DATA_PATH (used to run the tests and notebooks on
another machine); by default it is the data folder on nicodesktop.

Four zones:
    store01_rawzone         raw IBKR minute bars (corrected once for bad ticks, records/bad_tick_corrections.csv)
    store02_workzone        pipeline per-day features (steps 00-04) and the daily table (step 06)
    store03_goldzone        pipeline barrier targets (step 05)
    store04_experiments     everything an experiment produces, one folder per experiment, plus the shared trial log

Pipeline data (zones 1-3) is shared and kept across experiments. Experiment data (zone 4) can always be regenerated by
re-running the experiment's notebooks; deleting an experiment's folder never affects another experiment.
"""

# DEFINE THE DATA ROOT (ENVIRONMENT OVERRIDE OR THE DEFAULT FOLDER ON NICODESKTOP)
LOCAL_PATH_STR = os.environ.get("SO_DATA_PATH", "C:/Users/nico/Desktop/stock_overflow_data/").replace("\\", "/").rstrip("/") + "/"

# DEFINE THE ZONES
LOCAL_RAWZONE_PATH_STR = f"{LOCAL_PATH_STR}store01_rawzone/"
LOCAL_WORKZONE_PATH_STR = f"{LOCAL_PATH_STR}store02_workzone/"
LOCAL_GOLDZONE_PATH_STR = f"{LOCAL_PATH_STR}store03_goldzone/"
LOCAL_EXPERIMENTZONE_PATH_STR = f"{LOCAL_PATH_STR}store04_experiments/"

"""
Rawzone
"""

# DEFINE THE RAW IBKR MINUTE BARS FOLDER (YEARLY FILES)
LOCAL_OHLCV_DATA_FILE_PATH_STR = f"{LOCAL_RAWZONE_PATH_STR}ibkr_spy_1min/"

"""
Pipeline (shared by every experiment)
"""

# DEFINE THE PIPELINE FOLDERS (STEPS 00-04: WORKZONE)
LOCAL_DQ_REPORT_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step00_data_quality_report/"
LOCAL_PA_OHLCV_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step01_PA_ohlcv_data/"
LOCAL_TSIND_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step02_TSIND_data/"
LOCAL_TSSEG_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step03_TSSEG_data/"
LOCAL_TSCTX_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step04_TSCTX_data/"
# DEFINE THE BARRIER TARGET FOLDER (STEP 05: GOLDZONE)
LOCAL_TSBAR_DATA_FILE_PATH_STR = f"{LOCAL_GOLDZONE_PATH_STR}step05_TSBAR_data/"
# DEFINE THE DAILY TABLE FOLDER (STEP 06: WORKZONE; THE RECORD OF THE TABLE THAT DAILY EXPERIMENTS REBUILD IN MEMORY)
LOCAL_TSDAY_DATA_FILE_PATH_STR = f"{LOCAL_WORKZONE_PATH_STR}step06_TSDAY_data/"

"""
Experiments
"""

# DEFINE THE SHARED TRIAL LOG (EVERY EXPLORATION, SIGNAL CHECK, VALIDATION CANDIDATE AND TEST OF EVERY EXPERIMENT)
LOCAL_TRIAL_LOG_FILE_PATH_STR = f"{LOCAL_EXPERIMENTZONE_PATH_STR}trial_log.csv"

# FUNCTION: GET THE DATA FOLDER OF AN EXPERIMENT STEP
def get_experiment_data_path_str(experiment_name_str_in, folder_name_str_in):
    """
    Returns the folder where an experiment step writes its outputs: store04_experiments/<experiment>/<folder>/.

    Args:
        experiment_name_str_in (str): Experiment name, e.g. "exp02_stop_reentry"
        folder_name_str_in (str): Step folder, e.g. "step03_walk_forward_data"

    Returns:
        str: Folder path (ending with "/")
    """
    # RETURN THE FOLDER PATH
    return f"{LOCAL_EXPERIMENTZONE_PATH_STR}{experiment_name_str_in}/{folder_name_str_in}/"
