"""
VIX Family Constants (shared by the VIX data layer and the VIX experiments exp08-exp11; roadmap 2026-10-09)

Kept apart from so/config.py on purpose: so/config.py must not change (its constants enter the config hash of every
earlier experiment). Each VIX experiment's config.py assigns the values it uses to its own UPPERCASE constants, so its
config hash covers them.

Data: IBKR VIX and VIX3M index bars (daily and 1-minute) in store01_rawzone/ibkr_vix_family/, approved by Nicolas on
2026-10-08 (research-integrity.mdc, "Never 2"; inventory docs/VIX_DATA_INVENTORY_2026-10-08.md). Read only, never the
staging folder, never the backup folders.
"""

# DEFINE THE SERIES
VIX_SERIES_STR_LIST = ["vix", "vix3m"]
# DEFINE THE FOLDER KEYS (ATTRIBUTE OF so.paths OF EACH SERIES AND BAR SIZE)
VIX_FOLDER_KEY_DICT = {
    ("vix", "daily"): "LOCAL_VIX_DAILY_DATA_FILE_PATH_STR",
    ("vix", "1min"): "LOCAL_VIX_1MIN_DATA_FILE_PATH_STR",
    ("vix3m", "daily"): "LOCAL_VIX3M_DAILY_DATA_FILE_PATH_STR",
    ("vix3m", "1min"): "LOCAL_VIX3M_1MIN_DATA_FILE_PATH_STR",
}
# DEFINE THE FILE NAME PREFIX (DAILY: ohlcv_data_YYYY.csv; 1-MINUTE: ohlcv_data_YYYYMMDD.csv)
VIX_FILE_PREFIX_STR = "ohlcv_data_"

# DEFINE THE FIRST DAY OF THE UNTOUCHED WINDOW (EVERY LOADER REFUSES A CUTOFF ON OR AFTER IT)
UNTOUCHED_START_DATE_STR = "2026-05-14"
# DEFINE THE FIRST DATE OF EACH SERIES IN THE IBKR DATA
VIX_START_DATE_STR = "2005-10-03"
VIX3M_START_DATE_STR = "2009-08-12"
SERIES_START_DATE_DICT = {"vix": VIX_START_DATE_STR, "vix3m": VIX3M_START_DATE_STR}

# DEFINE THE STALENESS LIMIT OF THE PREVIOUS DAILY CLOSE (SPY SESSIONS BETWEEN ITS DATE AND THE PREVIOUS SPY SESSION)
STALE_MAX_SESSIONS = 3
# DEFINE THE MINIMUM LAG OF AN INTRADAY BAR LABEL BEFORE THE DECISION BAR (MINUTES)
INTRADAY_MIN_LAG_MINUTES = 1

# DEFINE THE FEATURE WINDOWS (SESSIONS)
PCT_WINDOW_SESSIONS = 250
CHG_SESSIONS = 5
FADE_WINDOW_SESSIONS = 20
# DEFINE THE ANNUALIZATION OF THE REALIZED VARIANCE (TRADING SESSIONS PER YEAR)
ANNUALIZATION_SESSIONS = 252
# DEFINE THE TIMING VARIANTS (PRIMARY: PREVIOUS DAILY CLOSE; SECONDARY: LAST 1-MINUTE BAR BEFORE THE DECISION)
VARIANT_STR_LIST = ["prev", "intraday"]
PRIMARY_VARIANT_STR = "prev"
# DEFINE THE FEATURE NAMES (THE COLUMN OF VARIANT v IS f"{name}_{v}")
VIX_FEATURE_BASE_STR_LIST = ["vix_level", "vix_pct250", "vix_chg5", "vix_fade", "vix_term", "vrp"]

# DEFINE THE KNOWN GAPS OF THE RAW DATA (INCLUSIVE DATE RANGES; docs/VIX_DATA_INVENTORY_2026-10-08.md, roadmap 2026-10-09)
KNOWN_GAP_DICT = {
    ("vix", "1min"): [("2006-05-01", "2006-05-19"), ("2011-09-12", "2011-09-12")],
    ("vix", "daily"): [("2006-05-01", "2006-05-19"), ("2006-11-24", "2006-11-24"), ("2011-09-12", "2011-09-12")],
    ("vix3m", "1min"): [("2011-09-12", "2011-09-12"), ("2017-10-20", "2017-10-20"), ("2017-10-23", "2017-10-24")],
    ("vix3m", "daily"): [("2011-09-12", "2011-09-12")],
}
# DEFINE THE HALF DAYS WHOSE VIX 1-MINUTE FILES WERE LEFT IN STAGING (NEVER READ; THE INTRADAY VALUE FALLS BACK TO _prev)
STAGED_HALF_DAY_STR_LIST = ["2020-11-27", "2020-12-24", "2024-07-03", "2024-12-24"]

# DEFINE THE SESSION-SHIFTED NULL (exp08: CIRCULAR SHIFT OF THE SIX VIX FEATURE COLUMNS AS ONE BLOCK)
NULL_RUN_COUNT = 19
NULL_SHIFT_SHARE_RANGE = (0.25, 0.75)
NULL_SEED = 20261009
